FROM pytorch/pytorch:1.12.0-cuda11.3-cudnn8-runtime

COPY requirements.txt /tmp/
RUN pip install --requirement /tmp/requirements.txt

RUN apt-get update
RUN apt-get install ffmpeg libsm6 libxext6  -y

WORKDIR /root

RUN mkdir /root/results 
RUN mkdir /root/results/rlad
RUN mkdir /root/rlad
RUN mkdir /root/memory

ENV PYTHONPATH="/root/rlad"
ENV RLAD_ROOT="/root/rlad"

ENV USER="deep"


